name: Build and Deploy Angular Project

on:
  push:
    branches:
      - master # 監聽 master 分支的 push 事件
  pull_request:
    branches:
      - master # 也可以在 pull request 事件中觸發

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact # NOTE: same artifact name
          path: my-file.txt
  upload-again:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact # NOTE: same artifact name
          path: my-file.txt
          overwrite: true
